workflows:
  ios-build:
    name: Build iOS App
    environment:
      vars:
        OPENAI_API_KEY: $OPENAI_API_KEY
    scripts:
      - echo "Starting iOS build..."
      - gem install cocoapods
      - pod install
    build:
      xcode_project: "App/PersonalAssistantApp.xcodeproj"
      xcode_scheme: "PersonalAssistantApp"
      export_method: "app-store"
