workflows:
  ios-build:
    name: Build iOS App
    environment:
      vars:
        OPENAI_API_KEY: $OPENAI_API_KEY
    scripts:
      - echo "Starting iOS build..."
    dependencies:
      before_install:
        - gem install cocoapods
    build:
      ios:
        project_path: "App"
        scheme: "PersonalAssistantApp"
