workflows:
  ios-build:
    name: Build iOS App
    environment:
      vars:
        OPENAI_API_KEY: $OPENAI_API_KEY
    scripts:
      - echo "Starting iOS build..."
      - gem install cocoapods
      - pod install --project-directory=App
      - xcodebuild -project App/PersonalAssistantApp.xcodeproj -scheme PersonalAssistantApp -sdk iphoneos -configuration Release clean build
